### ISSUE TITLE
Extension works on all sites

### ISSUE THREAD

**Issue by polarise-art-stankov** [Xatta-Trone/medium-parser-extension#20]
Hi, as this extension should only work on Medium, please make it do that. Because currently it can change some elements on other websites (for example GitHub), as it doesn't check which website you are on. I've been able to mitigate this for now by setting "Site access" option to "On specific sites" and adding "https://medium.com" there:
<img width="679" alt="image" src="https://github.com/Xatta-Trone/medium-parser-extension/assets/153196433/fafad166-c3a4-4c01-a696-4a0fb4a23e29">

**Comment by Xatta-Trone** [comment]
No, it works on the medium.com and all medium.com based sites (like towardsdatascience and all custom medium based sites). Because I can not list all the medium based site, so I had to come up with a better solution. 
Now, before running the script, it always checks if the content is from the medium CDN or not. If it is from the medium CDN, the script stops ( you can check the source code yourself for verification). Therefore, you have nothing to worry about.

**Comment by Xatta-Trone** [comment]
Moreover, if you want to run it only in medium.com, you can always restrict the access to medium.com.

**Comment by polarise-art-stankov** [comment]
> No, it works on the medium.com and all medium.com based sites (like towardsdatascience and all custom medium based sites). Because I can not list all the medium based site, so I had to come up with a better solution. Now, before running the script, it always checks if the content is from the medium CDN or not. If it is from the medium CDN, the script stops ( you can check the source code yourself for verification). Therefore, you have nothing to worry about.

Oh, didn't know that. Okay then, thanks for explanation
