### ISSUE TITLE
Some option ideas

### ISSUE THREAD

**Issue by vbmark** [Xatta-Trone/medium-parser-extension#25]
Hello,

First off, thank you for all you've done with this extension.  I really appreciate all your work.  

Here are a couple of ideas I have, please:

1. Below the buttons, a checkbox with a label, "Open in current tab."  Reason: I don't need another tab opened because then I have to close two tabs when I'm done reading.  Having the option to open in the current tab means only closing one tab when I am done reading.

2. Below the buttons, a drop-down box with the label, "Default site" with the drop-down's content of:

-- None
-- Open in Google Cache
-- Open in Read-Medium
etc...

When something other than "None" is selected, you don't have to click a button each time but you will automatically be redirected to the selected option.

If you are using the option to open the site in the current tab and you want to change the default site, then you can hit your browser's back button and the extension detects that you are navigating back so that you are not automatically sent to the site in the drop-down box again.

Reason: I really only use Google Cache and don't need the other options unless for some reason Google Cache isn't working.

Thank you again.

**Comment by Xatta-Trone** [comment]
Hello @vbmark,

Thank you very much for the ideas. I am waiting to cross 50k users to release the next update, where I will rewrite the whole extension and update the UI to improve it. 

I have a question about the second suggestion, is it something like, in the options you set the default site? Then when you visit a medium URL it will automatically redirect to that default site. If yes, I have seen this behavior in other Chrome extensions and am not a fan of this approach. Because what if the default URL does not work? then the user will have to go back again and try again. It was kinda annoying for me from a user's perspective. That is why I kept all the options available by default. Please let me know if my understanding is correct. 

Again, thank you very much for the ideas. I will take those into consideration for you.

**Comment by vbmark** [comment]
Thank you for your reply.

You are correct about how the second suggestion works and that is why the first option is "None" so that the feature is completely optional to use.  "None" means do not automatically go to any site.

I haven not personally had the google site not work, but in the unlikely case that there is a problem then I don't mind going back.  But, again, just select "None" if annoying.

Thank you.

**Comment by Xatta-Trone** [comment]
@vbmark hello there..how are you ?

https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/d6d396e0-183c-4069-9a41-294bd8fb6db5


I have been working on the updates and added some functionality those you have suggested...could you please check it in your local and confirm if it is working or not ? Then I will proceed with the final release. 

Here is the debug file:
[chrome.zip](https://github.com/Xatta-Trone/medium-parser-extension/files/15088317/chrome.zip)

**Comment by vbmark** [comment]
Very well done!  I really like the direction you went with the options and everything worked well.

The only issue I had was when I had, "Open in a new tab" unchecked and I clicked the back button the browser would go back to the original Medium article but then automatically redirect forward again.  The reason I occasionally wish to go back to the original article is because you can't read the comments on the cached sites.  

Other than that minor issue, I really like it.  Also, thank you for the instructional video on how to install it for testing.

Thank you!

**Comment by Xatta-Trone** [comment]
@vbmark Hello, 

Good news, I have just published the updated version today.
