### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by MeWannaSleep** [Xatta-Trone/medium-parser-extension#5]
Thx for your amazing work. but reading from the  google cache, I found some contents are not properly displayed,
![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/135443303/f80657e8-e36a-446a-bdd0-7e05597399bd)
I don't know whether it's because the data from google cache is broken or something else went wrong
the medium link is https://towardsdatascience.com/fine-tune-your-own-llama-2-model-in-a-colab-notebook-df9823a04a32

**Comment by Xatta-Trone** [comment]
I see why it happened.  The Google web cache does not include the hosted code snippets. That is why I have added archive.is as a fallback option. 

In your case, in the main code snippet 

`result = pipe(f"<s>[INST] {prompt} [/INST]")` In here, the `<s>` tag caused this issue. Because in the extension, it is parsing the HTML contents only. 

You can always revert to archive.is as a fallback using the `Read from Archive.is` button. 

![image](https://github.com/Xatta-Trone/medium-parser-extension/assets/22274105/e51cef0b-684b-4b8e-b4fa-ab9a96d46c26)

In the archive.is it is working okay.
Here is the link to URL https://archive.is/KrD7I#selection-1933.0-1941.1

@MeWannaSleep

**Comment by MeWannaSleep** [comment]
thx for your reply,
