### ISSUE TITLE
Bring back the 3rd party proxy option?

### ISSUE THREAD

**Issue by BenJackGill** [Xatta-Trone/medium-parser-extension#9]
Love this extension. It's the only one that works!

But I noticed that you removed the 3rd party proxy bypass option. I really preferred that over the new options.

This is because I can only access medium.com from behind a VPN which the Google cache has problems with and even once it loads it is often missing code snippets and some images. Also the web archive site is not as nice to read from.

Maybe the 3rd party proxy was costing you money? Which in that case I understand why you removed it.

But otherwise I would advocate for returning that option, alongside the new Google Cache and Web Archive options.

**Comment by Xatta-Trone** [comment]
To answer your questions. 

1. The third party proxy: 
` It was just an API over the Google Web Cache. Since I was already using google web cache behind the proxy site, therefore to reduce the loads/ unnecessary API calls I removed the third party proxy and directly served from the Google web cache. `

2. it is often missing code snippets and some images
`Google web cache does not include the iframe code snippets or anything for that matter (like iframe video). That is why I added archive.is as an alternate option where you can see including the iframe code snippets/videos. However, sometimes the article has not been archived yet in the archive.is; In that case you have to save the article in there first. 
To make that process easy, I have added some actions, where when you open the URL in archive.is, it automatically tries to submit the link. If there is an old record, it will show it, otherwise it will start collecting. 
`

3. I would advocate for returning that option, alongside the new Google Cache and Web Archive options
`Thank you for your concern, I will add this 3rd party API again in the next update. `


Hope this answers your question. If you have any, please do not hesitate to ask.

**Comment by Xatta-Trone** [comment]
@BenJackGill 

Hello, I have updated it based on your request. Please update the extension.
